### PR TITLE
init with vite, react, typescript and tailwind

### PR DESCRIPTION
**Pull request by nexxeln**
- set up a basic vite + react project
- set up eslint with basic rules for react and typescript projects
- set up tailwind
- set up prettier
- set up ci using github actions

### CODE REVIEW

**Comment by Meetesh-Saini** [comment]
> @Dhananjay-Chauhan I need write access, branch protection seems to be not configured

I have configured it.

**Comment by Dhananjay-Chauhan** [comment]
> @Dhananjay-Chauhan I need write access, branch protection seems to be not configured

@WizzyGeek Write access granted.

**Comment by Meetesh-Saini** [comment]
Why are you not using swc? @nexxeln

**Review by Dhananjay-Chauhan — APPROVED** [review]

**Comment by nexxeln** [comment]
> Why are you not using swc? @nexxeln

no need, vite is more than enough and also swc is a huge binary

**Comment by Meetesh-Saini** [comment]
> > Why are you not using swc? @nexxeln
> 
> no need, vite is more than enough and also swc is a huge binary

I agree that the vite is enough but swc offers faster compilation. The builds will take less time.

**Comment by nexxeln** [comment]
> I agree that the vite is enough but swc offers faster compilation. The builds will take less time.

our site isn't gonna be that big to make a meaningful difference. especially with vit wifi speeds where downloading a huge binary is gonna waste a lot of time

**Pull request merged**
